### ISSUE TITLE
[M] 🔒 Configurar Filtro de Autenticação JWT e Rotas no Gateway-Service

### ISSUE THREAD

**Issue by DudaWendelMaia** [T2-Projarc/task-manager-microservices#8]
- **✏️ Descrição:**
  - Implementar um filtro de autenticação JWT no gateway-service para validar os tokens antes de redirecionar as requisições aos microsserviços. Além disso, configurar as rotas no gateway para que cada microsserviço seja acessível por meio de URLs específicas.

- **📋 Critérios de Aceitação:**
  - O filtro de autenticação JWT deve:
    - Validar tokens JWT recebidos no cabeçalho Authorization de requisições.
    - Bloquear requisições com tokens ausentes ou inválidos, retornando o status HTTP apropriado.
    - As rotas do gateway-service devem estar configuradas para os seguintes microsserviços:
    - auth-service: Rotas acessíveis sem validação de token JWT.
    - task-service: Rotas protegidas por autenticação JWT.
    - notification-service: Rotas protegidas por autenticação JWT.

**Comment by MauricioKrziminski** [comment]
finished
